import pluginVue from 'eslint-plugin-vue'
import vueParser from 'vue-eslint-parser';

export default [
    ...pluginVue.configs['flat/recommended'],
    {
        files: ['**/*.js', '**/*.vue'],
        ignores: [
            'node_modules/',
            'bower_components/',
            '**/bootstrap.*.js',
            '**/bootstrap.js',
            '**/jquery.js',
            '**/jquery.*.js',
            '**/tether.js',
            '**/tether.*.js',
            'protractor.conf.js',
            'karma.conf.js',
        ],
        languageOptions: {
            parser: vueParser,
            ecmaVersion: 2022,
            sourceType: 'module',
            globals: {
                Atomics: 'readonly',
                SharedArrayBuffer: 'readonly',
                route: 'readonly',
                Ziggy: 'readonly',
                axios: 'readonly',
            },
        },
        rules: {
            'semi': 'warn',
            'quotes': 'off',
            'no-multi-spaces': 'off',
            'one-var': 'off',
            'no-console': 'off',
            'linebreak-style': 'off',
            'max-nested-callbacks': ['error', 4],
            'max-params': ['error', 8],
            'max-depth': ['error', 5],
            'max-lines-per-function': ['error', 300],
            'complexity': ['error', 31],
            'class-methods-use-this': 'off',
            'arrow-parens': ['error', 'always'],
            'vue/no-unused-vars': 'error',
            'vue/no-v-html': 'off',
            'vue/multi-word-component-names': 0,
            'vue/no-reserved-component-names': 'off',
            'vue/no-template-shadow': 'off',
            'vue/no-v-model-argument': 'off',
            'vue/no-v-text-v-html-on-component': 'off',
            'vue/html-indent': 'off',
            'vue/max-attributes-per-line': 'off',
            'vue/require-explicit-emits': 'off',
            'vue/html-self-closing': 'off',
            'vue/first-attribute-linebreak': 'off',
            'vue/no-unused-components': 'error',
            'vue/no-use-v-if-with-v-for': 'error',
            'vue/no-dupe-keys': 'error',
            'vue/no-duplicate-attributes': 'error',
            'vue/no-multiple-template-root': 'error',
            'vue/no-parsing-error': 'error',
            'vue/no-reserved-keys': 'error',
            'vue/no-reserved-props': 'error',
            'vue/no-side-effects-in-computed-properties': 'error',
            'vue/no-useless-template-attributes': 'error',
            'vue/no-v-for-template-key': 'off',
            'vue/require-v-for-key': 'error',
            'vue/return-in-computed-property': 'error',
            'vue/valid-attribute-name': 'error',
            'vue/valid-next-tick': 'error',
            'vue/valid-template-root': 'error',
            'vue/valid-v-else-if': 'error',
            'vue/valid-v-else': 'error',
            'vue/valid-v-for': 'error',
            'vue/valid-v-html': 'error',
            'vue/valid-v-if': 'error',
            'vue/valid-v-model': 'error',
            'vue/valid-v-on': 'error',
            'vue/valid-v-once': 'error',
            'vue/valid-v-pre': 'error',
            'vue/valid-v-show': 'error',
            'vue/valid-v-slot': 'error',
            'vue/valid-v-text': 'error',
            'vue/html-closing-bracket-newline': 'error',
            'vue/html-closing-bracket-spacing': 'off',
            'vue/html-quotes': 'error',
            'vue/multiline-html-element-content-newline': 'error',
            'vue/mustache-interpolation-spacing': 'error',
            'vue/no-multi-spaces': 'error',
            'vue/singleline-html-element-content-newline': 'error',
            'vue/attribute-hyphenation': 'error',
            'vue/component-definition-name-casing': 'error',
            'vue/html-end-tags': 'error',
            'vue/prop-name-casing': 'error',
            'vue/require-prop-types': 'error',
            'vue/v-bind-style': 'error',
            'vue/v-on-event-hyphenation': 'error',
            'vue/no-lone-template': 'error',
            'vue/no-multiple-slot-args': 'error',
            'vue/html-comment-indent': 'error',
            'vue/no-deprecated-model-definition': 'error',
            'vue/no-empty-component-block': 'error',
            'vue/no-required-prop-with-default': 'error',
            'vue/no-restricted-component-names': 'error',
            'vue/no-restricted-custom-event': 'error',
            'vue/no-restricted-props': 'error',
            'vue/no-root-v-if': 'error',
            'vue/no-template-target-blank': 'off',
            'vue/no-unsupported-features': 'error',
            'vue/no-useless-mustaches': 'error',
            'vue/no-useless-v-bind': 'off',
            'vue/prefer-true-attribute-shorthand': 'error',
            'vue/no-irregular-whitespace': 'error',
        },
    },
];
